//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capsule.TaskManager.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentTask
    {
        public ParentTask()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Parent_ID { get; set; }
        public string Parent_Task { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
